name: Continuous Integration

on: [push, pull_request, workflow_dispatch]

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python3 -m pip install pytest pytest-asyncio websockets

      - name: Install aiorpcX
        run: python3 setup.py install

      - name: Component test
        run: |
          cd tests
          python3 -m pytest
